lib/takemoney_web/router.ex
defmodule TakemoneyWeb.Router do
  use TakemoneyWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug TakemoneyWeb.Plugs.CurrentUser
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", TakemoneyWeb do
    pipe_through :browser # Use the default browser stack

    get "/", EventController, :index
    resources "/events", EventController, only: [:show]
    resources "/shopping_cart", ShoppingCartController, singleton: true
    resources "/sessions", SessionController, only: [:new, :create], singleton: true
    delete "/sessions", SessionController, :destroy
  end

  # Other scopes may use custom stacks.
  # scope "/api", TakemoneyWeb do
  #   pipe_through :api
  # end
end

lib/takemoney_web/views/layout_view.ex
defmodule TakemoneyWeb.LayoutView do
  use TakemoneyWeb, :view
end

lib/takemoney_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Hello Takemoney!</title>
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">
  </head>

  <body>
    <div class="container">
      <header class="header">
        <nav role="navigation">
          <ul class="nav nav-pills pull-right">
            <li>
              <%= link "Log out", to: session_path(@conn, :destroy), method: :delete %>
            </li>
          </ul>
        </nav>
        <span class="logo"></span>
      </header>

      <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>

      <main role="main">
        <%= render @view_module, @view_template, assigns %>
      </main>

    </div> <!-- /container -->
    <script src="<%= static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>